import os
import sys
import joblib
from fastapi import FastAPI, Request, Form
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Add project root to sys.path to resolve any local dependencies if needed
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.append(project_root)

app = FastAPI(title="Twitter Sentiment Analysis", description="Web interface for sentiment classification.")

# Mount static files
app.mount("/static", StaticFiles(directory=os.path.join(current_dir, "static")), name="static")

# Templates
templates = Jinja2Templates(directory=os.path.join(current_dir, "templates"))

# Global variables for model and vectorizer
model = None
vectorizer = None

# Paths to artifacts
# We expect the model and vectorizer to be generated by the training scripts
MODEL_PATH = os.path.join(project_root, "models", "LogisticRegression", "logistic_standard_TFIDF.joblib")
VECTORIZER_PATH = os.path.join(project_root, "data", "VECTORS", "tfidf_default.joblib")

@app.on_event("startup")
async def load_artifacts():
    global model, vectorizer
    try:
        logger.info(f"Loading vectorizer from {VECTORIZER_PATH}...")
        if not os.path.exists(VECTORIZER_PATH):
            logger.error(f"Vectorizer file not found at {VECTORIZER_PATH}. Please run training script first.")
            return

        # The vectorizer is stored inside a dictionary in the joblib file
        vector_data = joblib.load(VECTORIZER_PATH)
        if isinstance(vector_data, dict) and "vectorizer" in vector_data:
            vectorizer = vector_data["vectorizer"]
        else:
            logger.error("Could not find 'vectorizer' key in the loaded file.")
            return
        
        logger.info(f"Loading model from {MODEL_PATH}...")
        if not os.path.exists(MODEL_PATH):
            logger.error(f"Model file not found at {MODEL_PATH}. Please run training script first.")
            return
            
        model = joblib.load(MODEL_PATH)
        logger.info("Model and vectorizer loaded successfully.")
        
    except Exception as e:
        logger.error(f"Error loading artifacts: {e}")

class SentimentRequest(BaseModel):
    text: str

@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/predict")
async def predict_sentiment(request: SentimentRequest):
    if not model or not vectorizer:
        return JSONResponse(status_code=503, content={"error": "Model not loaded"})
    
    text = request.text
    try:
        # Preprocess / Vectorize
        # Note: The vectorizer expects an iterable of strings
        vectors = vectorizer.transform([text])
        
        # Predict
        prediction = model.predict(vectors)[0]
        
        # Map label to string if necessary (assuming 0=Neg, 1=Neut, 2=Pos or similar)
        # Check actual labels from the dataset. 
        # Usually: 0: Negative, 2: Neutral, 4: Positive (Twitter dataset standard)
        # OR: 0: Negative, 1: Neutral, 2: Positive
        # The code run_logistic_models.py doesn't plainly show mapping, but usually we map to user friendly text.
        
        # Let's return the raw prediction and map it in frontend or here if we knew map.
        # Based on typical datasets: 
        sentiment_map = {0: "Negative", 2: "Neutral", 4: "Positive"}
        # If the model was trained on mapped labels (0, 1, 2)
        sentiment_map_simple = {0: "Negative", 1: "Neutral", 2: "Positive"}
        
        # Fallback to string conversion
        sentiment = str(prediction)
        if isinstance(prediction, (int, float,  np.integer)):
             if int(prediction) in sentiment_map:
                 sentiment = sentiment_map[int(prediction)]
             elif int(prediction) in sentiment_map_simple:
                 sentiment = sentiment_map_simple[int(prediction)]

        return {"sentiment": sentiment, "score": float(prediction) if hasattr(prediction, "tolist") else prediction}
        
    except Exception as e:
        logger.error(f"Prediction error: {e}")
        return JSONResponse(status_code=500, content={"error": str(e)})

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
